spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  application:
    name: web-library
  datasource:
    url: jdbc:postgresql://localhost:5433/web_library
    username: sandr
    password: 57933
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true